### ISSUE TITLE
moo.s compile error

### ISSUE THREAD

**Issue by teverett** [DoctorWkt/pdp7-unix#110]
kato:pdp7-unix tom$ tools/as7 scans/moo.s 
I
II
scans/moo.s
scans/moo.s:450: standings not defined

**Comment by sebras** [comment]
> scans/moo.s:450: standings not defined

This is simply a typo in the original scans.
Changing it to `standing` and it will assemble successfully.
I wanted to keep the source code files true to the scans, so I kept the error in.

**Comment by teverett** [comment]
thanks

**Comment by philbudne** [comment]
> > scans/moo.s:450: standings not defined
>
> This is simply a typo in the original scans.
> Changing it to `standing` and it will assemble successfully.
> I wanted to keep the source code files true to the scans, so I kept the error in.

I suspect as.s silently truncates symbols to 8 characters, so the
"real fix" is to make as7 match as.s in that regard.

Right now as.s assembled under as7 and run under a7out on moo.s
outputs a large number of complaints, so validation of my theory
would need to be done by code inspection....

p
