### ISSUE TITLE
Readme.md missing ln command in typical run

### ISSUE THREAD

**Issue by decuser** [DoctorWkt/pdp7-unix#115]
I noticed the readme example no  longer has:
ln dd ken .

Is it no longer needed, or was it dropped by mistake?

**Comment by teverett** [comment]
I see it.... you don't?

**Comment by decuser** [comment]
No. Are you looking at latest?

**Comment by teverett** [comment]
This?

https://github.com/DoctorWkt/pdp7-unix/blob/master/README.md

**Comment by decuser** [comment]
Yup:

pdp7 unixv0.simh

PDP-7 simulator V4.0-0 Current        git commit id: aff3346e
CPU	idle disabled
	8KW, EAE
/Users/tom/projects/pdp7-unix/build/unixv0.simh-13> att rb image.fs
RB: buffering file in memory
/Users/tom/projects/pdp7-unix/build/unixv0.simh-18> att -U g2in 12345
Listening on port 12345
PDP-7 simulator configuration

CPU	idle disabled
CLK	60Hz, devno=00
PTR	devno=01
PTP	devno=02
TTI	devno=03
TTO	devno=04
LPT	disabled
DRM	disabled
RB	devno=71
DT	disabled
G2OUT	devno=05
G2IN	devno=43-44

login: ken
password: ken
@ ls system
system?
@ ls system
dd   

No ln dd ken .

**Comment by decuser** [comment]
Back in place, alls well that ends well.
