### ISSUE TITLE
as7 problem

### ISSUE THREAD

**Issue by larsbrinkhoff** [DoctorWkt/pdp7-unix#159]
I was looking into a problem with p (pool game).  I traced it to a location unexpectedly being 0.  It's `-bvsize` in putball.

I'm submitting a condensed test case.  This input:

```
        -y
x:
        .=.+1
y = .-x
```

results in this output:

```
010000: 000000          -y
```

**Comment by larsbrinkhoff** [comment]
Here is the --debug log:

```
I
parse_line: '   -y'
expression: '-y'
    '-y'
        found -
        sym: y
        syllable: 0 word: 0
        parse_expression => 0
parse_line: 'x:'
process_label x
Set global label x to 01000001
parse_line: '   .=.+1'
Got directive .=.+1
parse_line: 'y = .-x'
expression: ' .-x'
    '.-x'
        sym: .
        var: .: 01000001
        syllable: 01 word: 01
    '-x'
        found -
        sym: x
        lbl: x: 01000001
        syllable: 01 word: 0
        parse_expression => 0
Setting variable y to 00
II
tmp.s
parse_line: '   -y'
expression: '-y'
    '-y'
        found -
        sym: y
        var: y: 0
        syllable: 0 word: 0
        parse_expression => 0
parse_line: 'x:'
process_label x
Set global label x to 01000001
parse_line: '   .=.+1'
Got directive .=.+1
parse_line: 'y = .-x'
expression: ' .-x'
    '.-x'
        sym: .
        var: .: 01000001
        syllable: 01 word: 01
    '-x'
        found -
        sym: x
        lbl: x: 01000001
        syllable: 01 word: 0
        parse_expression => 0
Setting variable y to 00

**Comment by larsbrinkhoff** [comment]
I see "Got directive .=.+1".  In other cases were will result in a line "Setting variable . to N", but I don't see that here.

**Comment by philbudne** [comment]
I ran into (and fixed) an a7 problem found by tmg today:

	expr;foo=x;x=x+1

was not assembling properly.

The fix is in the original-commands branch, I want to see it get
some testing there before putting it into master.

(I'd like to merge the whole branch)

p

**Comment by larsbrinkhoff** [comment]
I tested your original-commands branch.  as7 still does the same with
the above input, and p too.

I also tested building and running the image.  No problems as far as
I can see, but I only did light testing.

**Comment by philbudne** [comment]
I'm seeing (in both master and original-commands branches):

phil@p27:~/pdp7-unix/scans$ cat xx.s
        -y
x:
        .=.+1
y = .-x
phil@p27:~/pdp7-unix/scans$ ../tools/as7 xx.s
I
II
xx.s
phil@p27:~/pdp7-unix/scans$ cat a.out 
010000: 777777	        -y

**Comment by larsbrinkhoff** [comment]
Tabs vs spaces matter here.  If the input is `<spaces>.=.+1` it works: -y assembles as 777777.  If the input is `<TAB>.=.1` it doesn't work: -y assembles as 000000.

In the p?.s files, there are tabs.

**Comment by larsbrinkhoff** [comment]
In the debug log, this is the expected output (no tabs):

```
parse_line: '   .=.+1'
expression: '.+1'
    '.+1'
       sym: .
       var: .: 01000001
       syllable: 01 word: 01
    '+1'
       found +
       found constant: 1
       syllable: 01 word: 02
       parse_expression => 01000002
Setting variable . to 01000002
```

With a tab character:

```
parse_line: '  .=.+1'
Got directive .=.+1
```

**Comment by larsbrinkhoff** [comment]
I tested replacing the pool game tabs with spaces, and that made it display the table and balls.  Previously it just exited.

**Comment by philbudne** [comment]
I just saw this code recently:

	# Assembler directives start with a tab and a .
	if ($line =~ m{^\t(\..*)}) {
	   parse_directive($1);
	   return;
	}

......



# Parse assembler directives. These were not in the original
# PDP-7 Unix source, but we need them so that we can write
# compilers that target this assembler.
sub parse_directive
{
  my $directive= shift;
  print("Got directive $directive\n") if ($debug);

  # Set this as a local label
  if ($directive=~ m{^\.local\s+(\S+)}) {
    $Islocal{$file}{$1}=1;
  }
}

**Comment by philbudne** [comment]
I've changed the directive prefix from TAB DOT to "@"
