### ISSUE TITLE
Closing braces `}` force exit 'ed'

### ISSUE THREAD

**Issue by xlucn** [DoctorWkt/pdp7-unix#237]
Sorry for bothering. I am not sure if this is the intended behavior, my build issue, or what else. As soon as I enter `}` in 'ed' command, 'ed' will exit immediately:

```
@ ed
edit
}@
```

**Comment by philbudne** [comment]
Here is the reason, in s7.s:

   sad o375             " interrupt char (TTY ALT MODE?)
   jmp intrp1           "  yes

It was my surmise that the console ALT MODE key on the console TTY
sent 0375 and was used as the "interrupt" character.

A quick search found this for the Teletype model 33:

https://deramp.com/downloads/teletype/TTY-33%20Theory%20of%20Operation.pdf?page=3
(see "Note 5")

The TTY33 was upper-case only, and early ASCII had neither lower case,
nor the {, |, }, or ~ characters. But at least for PDP-11 Unix,
Teletype model 37's were in wide use at Bell Labs, so the TTY33 manual
may not be correct, and I seem to recall that BTL's TTY37s may have
custom ordered, so it may be that NO manual will perfectly document
the behavior of console terminal.

**Comment by larsbrinkhoff** [comment]
PDP-6 software from MIT and Stanford typically regards 175 and/or 176 as Altmode.  I believe they used model 33 teletypes.

**Comment by xlucn** [comment]
Thank you both for the detailed explanations!

Although I don't fully understand these information, I can tell this is not quite a bug, but a disagreement between character sets and how the characters are represented.

So, as regard to this issue, maybe we can close it if there are no fixes and no more discussions. However, is there any workarounds to input `}` into a file?

**Comment by philbudne** [comment]
> However, is there any workarounds to input `}` into a file?

The B source files use $( and $) digraphs for { and }

https://github.com/DoctorWkt/pdp7-unix/blob/master/scans/ind.b
https://github.com/DoctorWkt/pdp7-unix/blob/master/scans/lcase.b

**Comment by xlucn** [comment]
Perfect! I know there are similar things for C, but didn't realize in the case of B. Thanks again, @philbudne !

Now I know the reason and a workaround, I will close this issue then (if there is no fix).

**Comment by drawkula** [comment]
With e.g. ...
```
$ grep g2in unixv0.simh 
set g2in ena
att -U g2in 12345
```
... in SIMH's config you can ...
```
~$ telnet localhost 12345
Trying ::1...
Connected to localhost.
Escape character is '^]'.


Connected to the PDP-7 simulator G2IN device


login: dmr
password: dmr
@ ed
edit
a
hello {[]}
.
p
hello {[]}
q
@ █
```
... use the braces without those effects.

I think, that's nicer than transliterating the braces.
