### ISSUE TITLE
Non-existent device, any way to fix this?

### ISSUE THREAD

**Issue by seifeslimene** [DoctorWkt/pdp7-unix#238]
Is it possible to run unixv0 with simh on ubuntu 22.04?

Here what's going on so far?

![2023-11-19_01-26](https://github.com/DoctorWkt/pdp7-unix/assets/57100260/76d19246-dba7-4fd3-8ac6-8d0aaba1aea7)
![2023-11-19_01-27](https://github.com/DoctorWkt/pdp7-unix/assets/57100260/c93050e8-dc17-4fb9-a7ee-c5d6975c6ad2)
![2023-11-19_01-29](https://github.com/DoctorWkt/pdp7-unix/assets/57100260/92d1332a-c456-456f-9478-14018ce1f30a)

**Comment by philbudne** [comment]
Try building simh from https://github.com/open-simh/simh or https://github.com/simh/simh

Binary packages may be available, but I have no experience in that area.

**Comment by SeifESlimene** [comment]
I tried to build https://github.com/simh/simh using command "make", and it finished successfuly.
But then nothing happened I still have v3.8-1.

**Comment by philbudne** [comment]
running make should leave the new binaries in the BIN directory.

**Comment by seifeslimene** [comment]
> running make should leave the new binaries in the BIN directory.

Gotcha, I already deleted my previous comment :grin:
It works just fine now, thank you so much :heart_eyes:
