### ISSUE TITLE
/binaries directory missing 

### ISSUE THREAD

**Issue by rsanchov** [DoctorWkt/pdp7-unix#66]
Hi
Even if referenced in readme file, the /binaries directory is missing in the current GitHub
It would be great to have image.fs and boot.rim available do to a test-run without having to build them from scratch.
Is this possible?

Best regards

**Comment by teverett** [comment]
I believe there had been a binaries directory previously, however it was deleted.  At this point I'm not sure if the primary project contributors would support restoring it, or not.

**Comment by teverett** [comment]
ok, try the binaries in the /binaries dir.

**Comment by DoctorWkt** [comment]
I'm happy to have a binaries folder populated with stuff. Thanks Tom!

**Comment by rsanchov** [comment]
Hi Tom
Many thanks for restoring binaries.I'ts not easy to build unix from source for win people likeme, I'm happy to have the chance to test drive unixv0 :-)
Best RegardsRoberto


    On Wednesday, December 21, 2016 11:07 AM, Warren <notifications@github.com> wrote:
 

 I'm happy to have a binaries folder populated with stuff. Thanks Tom!—

**Comment by teverett** [comment]
Happy to help.
