### ISSUE TITLE
What about a possible tree of source (*.C) to build the full system?

### ISSUE THREAD

**Issue by spartrekus** [DoctorWkt/pdp7-unix#69]
Hello,

What about having a directory with all those files (*.c source code), which will allow to build System v7?

Still many of those programmes can be compiled with TCC or GCC under Linux or BSD (with adaptations).
http://www.tuhs.org/cgi-bin/utree.pl?file=V7

Ex:
        cal       col     diff     f77     kill     m4      nm      prof    rev    spell   t450  touch  uux
ac        calendar  comm    diff3    factor  ld       mail    nohup   ps      rm     spline  tabs  tp     vplot
adb       cat       cp      du       false   learn    make    nroff   pstat   rmdir  split   tail  tr     vpr
ar        cb        crypt   dump     fgrep   lex      man     od      ptx     roff   strip   tar   troff  wc
arcv      cc        cu      dumpdir  file    lint     mesg    osh     pwd     sa     struct  tbl   true   who
as        checkeq   date    echo     find    ln       mkdir   passwd  quot    sed    stty    tc    tsort  write
at        chgrp     dc      ed       graph   login    mv      pcc     random  sh     su      tee   tty    xget
awk       chmod     dcheck  egrep    grep    look     ncheck  plot    ranlib  size   sum     tek   uniq   xsend
bas       chown     dd      enroll   icheck  lookbib  neqn    pr      ratfor  sleep  sync    test  units  yacc
basename  clri      deroff  eqn      iostat  lorder   newgrp  prep    refer   sort   t300    time  uucp   yes
bc        cmp       df      expr     join    ls       nice    primes  restor  sp     t300s   tk    uulog

Best regards
Spartrekus

**Comment by teverett** [comment]
I like the idea, but unless I am confused, TCC can only generate i386 binaries.

https://bellard.org/tcc/tcc-doc.html#SEC1

We would need a compiler that can generate PDP-7 binaries

**Comment by DoctorWkt** [comment]
I've written a compiler for the PDP-7 that takes a sort-of-C language as input: https://github.com/DoctorWkt/h-compiler. However, PDP-7 Unix has completely different system calls than 7th Edition Unix, and the memory available to processes is only 4K. This would make it impossible to back-port C source code from 7th Edition Unix to the PDP-7 version of Unix.

However, it would be possible to rewrite cut-down versions of system utilities in the sort-of-C language that the compiler supports. I started to do this when I wrote the compiler.
Cheers, Warren

**Comment by fwortner** [comment]
What is the goal?  If it is to produce a replica of PDP7 Unix, then
backporting programs from V7 is not in service of that goal.  It’s like
putting a modern engine into a classic car — at least in my opinion.  It
would be an anachronism at best.  Of course, anyone can take the two and
combine them as a personal project.  The result is just not historical
restoration IMHO.
-- 
"Jazz music stimulates the minds and uplifts the souls of those who play it
was well as of those who listen to immerse themselves in it. As the mind is
stimulated and the soul uplifted, this is eventually reflected in the
body." -- Horace Silver

**Comment by DoctorWkt** [comment]
I agree entirely. The restoration of PDP-7 Unix has progressed as far as we can take it. The system, as it is, can be modified or extended etc., but this would no longer be a restoration. The restoration goal is complete. and there is no need (in this repository) to add anything else. But if there is a different goal, then the repo can be cloned.
