### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by teverett** [DoctorWkt/pdp7-unix#72]
It looks like this link, to the pdf's is 404.  Is there a new link to the pdfs?

http://www.tuhs.org/Archive/Research/McIlroy_v0/

**Comment by philbudne** [comment]
Looks like it's here:
https://www.tuhs.org/Archive/Distributions/Research/McIlroy_v0/

**Comment by DoctorWkt** [comment]
Thanks for fixing the broken link Phil!
