### ISSUE TITLE
PDP-7 unix code

### ISSUE THREAD

**Issue by teverett** [DoctorWkt/pdp7-unix#74]
https://computerhistory.org/blog/the-earliest-unix-code-an-anniversary-source-code-release/

so, are we going to add this to pdp7-unix?

**Comment by DoctorWkt** [comment]
Yes, of course! There is a mailing list for the previous work here: contact me if you want to be added. Robert Swierczek has already said:
I will be happy to start transcribing 13-120-147.pdf if there is no objection.
What do you think of one file per page (p120-stat.txt, p121-stat.txt, etc.)
with annotations in all upper-case to the right marked with <---??? or
some such. This should help with dividing up the work, proof-reading, etc.
