### ISSUE TITLE
License of the original sources?

### ISSUE THREAD

**Issue by rekado** [DoctorWkt/pdp7-unix#8]
Is the LICENSE file in the project directory supposed to mean that all of the sources are covered under GPLv3 or later?  Are the licenses of the original sources known or are they "all rights reserved" by default?  If so, are only the source files created from scratch to be considered covered under the GPLv3 or later?

It would be nice if this could be clarified.

**Comment by DoctorWkt** [comment]
That's a good question, redako. The tools/ files which are not part of the scans are under GPL3. The scans themselves are more problematic. Novel still own the rights to the Unix source code, so technically they are the people you should ask. Yes, I should put a copyright notice in the scans area and update the Readme.md.
