### ISSUE TITLE
compile errors on un.s

### ISSUE THREAD

**Issue by teverett** [DoctorWkt/pdp7-unix#85]
I
II
scans/un.s
scans/un.s:11: t1 not defined
scans/un.s:19: t1 not defined
scans/un.s:23: t1 not defined
scans/un.s:25: t1 not defined
scans/un.s:26: ca1 not defined

**Comment by sebras** [comment]
Thank you for telling me to check using `tools/as7 scans/un.s`. That was really helpful. 

I ran the command for `ttt{1,2}.s` and `un.s` and I found more transcription issues.
But e.g. the complaint `t1 not defined` I don't understand how to fix. So my proposed change will only fix this issue partially.

**Comment by teverett** [comment]
Fixed
